initial_insulin_dose:
  description: 'Based on the patient data, determine the initial insulin dose.'
  agent: 'initial_dose'
  expected_output: 'Insulin dose recommendation'

basal_insulin_dose:
  description: 'Based on the patient data, determine the appropriate basal insulin dose.'
  agent: 'basal'
  expected_output: 'Basal insulin dose recommendation'

rapid_insulin_dose:
  description: 'Based on the patient data, determine the appropriate rapid insulin dose.'
  agent: 'rapid'
  expected_output: 'Rapid insulin dose recommendation'

hyper_hypoglycemia_warning:
  description: 'Based on the patient data, detect any signs of impending hyperglycemia or hypoglycemia.'
  agent: 'warning'
  expected_output: 'Warnings for hyperglycemia or hypoglycemia'